monome/norns-community

- community.json
also changed my attributions from Matthew to Mat.
> adds "combos" collection

- community.json
added cheat codes to project manager <3
> add cheat_codes

- community.json
Adds a new filter script and engine.
> Adds Phyllis

- pull_request_template.md
@ngwese + @pq, does this work as a PR template for user contributions?
> create pull request template

- community.json
Added in an entry for my Islands script
> added Islands script

- community.json
I think I did this right, let me know if not!
> Add Caliper script

- community.json
Add an entry for the Pedalboard script https://llllllll.co/t/pedalboard-chainable-fx-for-norns/31119
> Add Pedalboard

- community.json
> remove redundant norns tags

- community.json
Adds grendy, a simple drone synth.
> Add grendy

- community.json
Resubmitting for Torii and Grid-Test. 
Also alphabetized the other entries at the end that were not alpha sorted.
> Add Torii, Grid-Test, alphabetize

- community.json
https://llllllll.co/t/cyrene-a-drum-sequencer-based-on-mutable-instruments-grids-v0-9-2/31648
> Add cyrene

- community.json
Adds rudiments, an 8 voice lofi percussion synthesizer and sequencer.
> Add rudiments script

- community.json
> adding grd

- community.json
> Adding Stjörnuíþrótt drone synth

- community.json
https://llllllll.co/t/foundry-font-visualizer/33933
> add foundry font visualizer

- community.json
> add just-play project

- community.json
https://llllllll.co/t/34095 / https://github.com/21echoes/samsara
> Add Samsara

- community.json
Adding b-b-b-b-beat https://llllllll.co/t/b-b-b-b-beat-ableton-beat-repeat-v0-0-4/35047
> Added b-b-b-b-beat

- community.json
i was [asked](https://llllllll.co/t/barcode/35297/30) to include add *barcode* to maiden.
please let me know if there is something i should do.
thanks!
> add barcode

- community.json
A small library with demos to generate Nørgård infinity sequences for Norns
> Adding noergaard library

- community.json
> Add Euclidigons

- community.json
> lower case yggdrasil

- community.json
> add cheat codes 2

- community.json
Added gridstep https://llllllll.co/t/38559 to the community catalog.
> Added gridstep

- community.json
Can I add breakthrough to the community repo please
> add breakthrough

- community.json
Adds entry for delayyyyyyyy - a warm, playable delay effect w/stereo separation and modulation.
> Add delayyyyyyyy

- community.json
Adds `blippoo`, a clone of the Blippoo Box.
> Add blippoo

- community.json
added spirals sequencer script
> added spirals

- community.json
> adds crow_talk

- community.json
@dndrks , i copied your naming from cc2, hope that'll be right.
> LC3 (third time's the charm)

- community.json
> add 4 Big Knobs

- community.json
just to solve the confusion :)
> remove cheat codes 1

- community.json
metrix added
https://github.com/kasperbauer/metrix
:)
> add metrix

- community.json
some testing ahead of opening the flood gates
> initial doc urls for testing

- community.json
As per https://llllllll.co/t/norns-update-210411/43926, add documentation_url to 21echoes's scripts
> Add documentation_url to 21echoes's scripts

- community.json
{
"project_name": "SuperBrain",
"project_url": "https://github.com/BeatRossmy/SuperBrain",
"author": "beat",
"description": "a five track sequencer with various sequencer engines per track",
"discussion_url": "https://llllllll.co/t/superbrain-multi-engine-midi-sequencer",
"tags": ["grid", "midi", "sequencer"]
}
> added SuperBrain

- community.json
Split in multiple commits, by authors, but don't hesitate to squash & merge reduce to a single commit.
> Added doc links for all scripts on norns.community

- community.json
I'd like to add my Loud Numbers data sonification script to the community repo
> Adding Loud Numbers

- community.json
To make it available through maiden.
> Add rangl to community.json

- community.json
Adding a new script of mine. Also tweaking the attribution slightly on my Loud Numbers script and putting it in the right place alphabetically.
> Adding gridofpoints

- community.json
Non-urgent. I updated the script and so needed to update the description.
> Tweak description

- community.json
to fix automatic installation location.
> Change `acid test` to `acid-test`

- community.json
will update with `discussion_url` when I post it
> add acrostic

- community.json
added constellations to community.json
> added constellations

- community.json
https://norns.community/en/authors/obi/fibonacci
> Add fibonacci

- community.json
Based on feedback from https://llllllll.co/t/fibonacci/54153.
> Update fibonacci script URLs

- community.json
Plus adding a MIDI tag to reflect new functionality
> Updating Loud Numbers URLs after moving the repo

- community.json
Added script 'raft' to the list of community scripts.
> Add raft to community.json

- community.json
First time for everything so hopefully I did it right.
> Added Giro looper

- community.json
removing a few scripts/libs I'm no longer maintaining (I am the author of all of them).
> remove msh, supercut, nest_

- community.json
so it shows up correctly in script list on norns
> un-capitalize n.kria

- community.json
Following instructions at https://monome.org/docs/norns/maiden/#contribute--gather
> Add midi-review to catalog.

- community.json
discovered this while doing some automatic processing on the catalog file. might be more soon as i clean it up.
> author fix

- community.json
fixes #245
~~DO NOT MERGE: i have not yet tested this with maiden and am concerned that the datatype variation of collab projects will cause breakage.~~
1. url-safe (one word) `author` field
2. ~~collabs are a list, not a string~~
thanks to @p3r7 for the initial scrub with python, which i hand-cleaned and corrected with vim macros
> New format

- community.json
> add streams

- base.json
> add fledge

- community.json
> add bitebeet

- community.json
'synths' -> 'synth' and 'sequencers' -> 'sequencer'
> bline: adjust tagging

- community.json
Add the Tidbit script to the community page.
> Add Tidbit

- community.json
thanks for the adding the script. best, sacha
> add justharmonicon

- community.json
> fix link rot

- community.json
Added my project https://github.com/smonthms/gridofrings to community.json - cheers!
> Update community.json to include gridofrings

- community.json
> added path-trace

- community.json
Jumped `arp_index` over `ash` and added `asterion`.
> add asterion and alphabetize arp

- community.json
url, description, and tag updates
> updates to dreamsequence, combiner, cybermidi

- community.json
Adding entry for tetra library
> Updated community.json 

- community.json
> edit nameless-nightmare

- community.json
> Added taweeet

- community.json
To update the community catalogue as this script gains new capabilities.
> Clockabout is now a mod; conform to formatting style

- community.json
I just added the MNMPatch script. Sorry for the earlier mistake, I created a pull cancelled and made this new one!
Cheers
> Added MNMPatch script

- community.json
Fixed a little author typo for infinitedigits.
> Fix typo for infinitedigits.

- community.json
Added fixed filter banking crisis.
> Added fixed filter banking crisis, a norns script.

- community.json
Without blank in the project name this time. Sorry for inconvenience 🙊
> Add fixed filter banking crisis

- community.json
> Added window crowparator, which comes with druid-only script too.

- community.json
Adds a generative ambient script called Avonlea by @kurogedelic to the community catalog.
Repository: https://github.com/kurogedelic/avonlea  
Discussion: https://llllllll.co/t/avonlea/71994
> Add Avonlea script by kurogedelic

- community.json
Adding my script to the community catalogue
> Adding hs010 to community scripts

- community.json
Adding a few additional tags that reflect new features in recent updates.
> Updating gridofpoints tags and description

- community.json
> updating project name for _awed

- community.json
sorry to try this again, but for some reason my last attempt didn't quite work. Maybe this will.
> Update community.json with _awed naming correction

- community.json
The Loud Numbers script seems to have vanished at some point - re-adding it back again now.
> Re-add Loud Numbers script
